### ISSUE TITLE
beam search bug

### ISSUE THREAD

**Issue by lijianxing123** [vllm-project/vllm#644]
There is a problem with the implementation of vllm beam search. It seems that the previous search results have been fixed and unchanged. Can you provide some help

**Comment by lijianxing123** [comment]
thanks

**Comment by thisissum** [comment]
I tried the implementation of  #646 , the output is aligned with hf perfectly.
But there are some concurrency problem in this implementation, the api server throws "IndexError: list index out of range" when I request it with 2 threads and get stucked.

**Comment by hsm1997** [comment]
hi @thisissum , I tried debugged with the concurrency problem, and I found that:
1. prompt batching is not broken
2. if you set use_beam_search=False and use sampling, thereis no concurrency problem with my codebase
3. for beam seach, looking into vllm/engine/llm_engine.py->step(), I found that at some time the returned `seq_groups`  has 0 seqs (which causes the IndexError)  and has a different request_id  with the `running` seq groups:

I'm not sure which part of my implementation causes the concurrency problem, or could the maintainers kindly offer some advice? Thanks!

```python3
324             seq_groups = self.scheduler.update(
325                 output,
326                 partial(detokenize_incrementally,
327                         tokenizer=self.tokenizer,
328                         skip_special_tokens=True))
329  
330             # Free the finished sequence groups.
331             self.scheduler.free_finished_seq_groups()
332  
333             # Create the outputs.
334             request_outputs: List[RequestOutput] = []
335             for seq_group in seq_groups + scheduler_outputs.ignored_seq_groups:
336                 try:
337                     request_output = RequestOutput.from_seq_group(seq_group)
338                 except:
339                     import pdb;pdb.set_trace()
340  ->             request_outputs.append(request_output)
341  
342             if self.log_stats:
343                 # Log the system stats.
344                 self._log_system_stats(scheduler_outputs.prompt_run,
345                                        scheduler_outputs.num_batched_tokens)
346             return request_outputs
(Pdb) self.scheduler.running
[SequenceGroup(request_id=cmpl-cad8ce19a8c34df0aba44eb5eb33bbea, sampling_params=SamplingParams(n=5, best_of=5, presence_penalty=0.0, frequency_penalty=0.0, temperature=0.0, top_p=1.0, top_k=-1, use_beam_search=True, stop=[], ignore_eos=False, max_tokens=1024, logprobs=None), num_seqs=5)]
(Pdb) seq_groups
[SequenceGroup(request_id=cmpl-7b8e9dddd5ab4c0c9e7917e30e65ea3e, sampling_params=SamplingParams(n=5, best_of=5, presence_penalty=0.0, frequency_penalty=0.0, temperature=0.0, top_p=1.0, top_k=-1, use_beam_search=True, stop=[], ignore_eos=False, max_tokens=1024, logprobs=None), num_seqs=0)]
(Pdb) seq_groups_1 = self.scheduler.update(output, partial(detokenize_incrementally,tokenizer=self.tokenizer,skip_special_tokens=True))
(Pdb) seq_groups_1
[SequenceGroup(request_id=cmpl-cad8ce19a8c34df0aba44eb5eb33bbea, sampling_params=SamplingParams(n=5, best_of=5, presence_penalty=0.0, frequency_penalty=0.0, temperature=0.0, top_p=1.0, top_k=-1, use_beam_search=True, stop=[], ignore_eos=False, max_tokens=1024, logprobs=None), num_seqs=4)]
```

**Comment by hsm1997** [comment]
hi @thisissum , I think the concurrency problem is fixed by now. I've tried up to 5 concurrent queries and things worked out fine in my case.

**Comment by thisissum** [comment]
hi @hsm1997 , thanks a lot for fixing the concurrency problem mentioned above, but I met another problem: 
I tried to use 5 concurrent queries to request the api server 1000 times, it seems that the llm_engine stop working after 500-600 requests while the fastapi app can still receive requests. This phenomenon happens randomly and still happens after I decrease the concurrency to 1.

**Comment by thisissum** [comment]
> hi @hsm1997 , thanks a lot for fixing the concurrency problem mentioned above, but I met another problem: I tried to use 5 concurrent queries to request the api server 1000 times, it seems that the llm_engine stop working after 500-600 requests while the fastapi app can still receive requests. This phenomenon happens randomly and still happens after I decrease the concurrency to 1.

I did more experiments and find that if I print self.block_manager.get_num_free_gpu_blocks() in scheduler, the num of free gpu blocks keeps decreasing. The llm_engine stop working after the num of free gpu blocks descrease to a very low number.

**Comment by hsm1997** [comment]
hi @thisissum , I think the memory leak problem is fixed now (by simply removing one redundant block_manager.fork statement). I tested with 3 concurrent threads, EACH queried the api server for about 200 times, all queries succeeded and the`num_free_gpu_blocks` does not always decreases.

**Comment by thisissum** [comment]
hi @hsm1997 , I tested again and I'm sure that the problem is fixed. Thanks a lot

**Comment by zhuohan123** [comment]
Fixed by #857. Please raise a new issue if there is any new error.
